# Generated by Django 5.2.14 on 2026-05-21 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.CharField(max_length=10, unique=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.item')),
            ],
            options={
                'db_table': 'warehouse_slots',
            },
        ),
    ]
