# Generated by Django 5.2.14 on 2026-05-21 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('intake', '적재'), ('pickup', '수령반환'), ('return', '창고복귀'), ('discard', '폐기')], max_length=20)),
                ('status', models.CharField(choices=[('pending', '대기중'), ('running', '수행중'), ('success', '완료'), ('failed', '실패')], default='pending', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
            options={
                'db_table': 'robot_tasks',
            },
        ),
    ]
