# Generated by Codex on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='reasoning',
            field=models.TextField(blank=True, default=''),
        ),
    ]
