# Generated by Django 5.2.14 on 2026-05-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('Card', '카드'), ('Glasses', '안경'), ('Keys', '열쇠'), ('Phone', '휴대폰'), ('Sunglasses', '선글라스'), ('Wallet', '지갑'), ('Watch', '시계')], max_length=20)),
                ('lost_location', models.CharField(blank=True, max_length=100, null=True)),
                ('lost_description', models.TextField()),
                ('status', models.CharField(choices=[('searching', '찾는중'), ('matched', '매칭완료'), ('completed', '수령완료')], default='searching', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
