# Generated by Django 5.2.15 on 2026-06-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='lost_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
