# Generated by Django 5.2.14 on 2026-06-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_lost_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('card', '카드'), ('glasses', '안경'), ('wallet', '지갑'), ('phone', '휴대폰'), ('keys', '열쇠'), ('sunglasses', '선글라스'), ('watch', '시계'), ('etc', '기타')], max_length=20),
        ),
    ]
