# Generated by Django 5.2.14 on 2026-06-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='auth_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='report',
            name='receiver_image',
            field=models.ImageField(blank=True, null=True, upload_to='pickup_photos/'),
        ),
    ]
