# Generated by Codex on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_auth_code_report_receiver_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('searching', '찾는중'), ('review', '검토필요'), ('matched', '매칭완료'), ('processing', '이송중'), ('completed', '수령완료')], default='searching', max_length=20),
        ),
    ]
