# Generated by Django 5.2.14 on 2026-06-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('Card', '카드'), ('Glasses', '안경'), ('Wallet', '지갑'), ('Phone', '휴대폰'), ('Keys', '열쇠'), ('Sunglasses', '선글라스'), ('Watch', '시계'), ('Etc', '기타')], max_length=20),
        ),
    ]
