# Generated by Django 5.2.14 on 2026-05-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Card', '카드'), ('Glasses', '안경'), ('Keys', '열쇠'), ('Phone', '휴대폰'), ('Sunglasses', '선글라스'), ('Wallet', '지갑'), ('Watch', '시계')], max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo_path', models.CharField(blank=True, max_length=255, null=True)),
                ('found_location', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('stored', '보관중'), ('matched', '매칭완료'), ('returned', '반환완료'), ('expired', '기간만료'), ('discarded', '폐기완료')], default='stored', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
