# Generated by Django 5.2.15 on 2026-06-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photo_path',
        ),
        migrations.AddField(
            model_name='item',
            name='found_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image_b64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='warehouse_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Card', '카드'), ('Glasses', '안경'), ('Keys', '열쇠'), ('Phone', '휴대폰'), ('Sunglasses', '선글라스'), ('Wallet', '지갑'), ('Watch', '시계'), ('Etc', '기타')], max_length=20),
        ),
    ]
