# Generated by Django 5.2.15 on 2026-06-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_photo_path_item_found_at_item_image_b64_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='found_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='found_location',
        ),
        migrations.AddField(
            model_name='item',
            name='found_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
